server: use dot instead of colon
Fixes the following error

```
ReferenceError: env is not defined
    at Object.<anonymous> (/Users/scanf/src/github.com/imba/hello-world-imba-sfc/src/server.imba:28:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at run (/Users/scanf/src/github.com/imba/hello-world-imba-sfc/node_modules/imba/bin/imba:47:15)
    at main (/Users/scanf/src/github.com/imba/hello-world-imba-sfc/node_modules/imba/bin/imba:98:9)
    at Object.<anonymous> (/Users/scanf/src/github.com/imba/hello-world-imba-sfc/node_modules/imba/bin/imba:101:1)
```